# API Credentials Configuration
# This file should be kept secure and not committed to version control

# Korea Investment & Securities (KIS) API
kis_api:
  real_account:
    app_key: "YOUR_KIS_REAL_APP_KEY"
    app_secret: "YOUR_KIS_REAL_APP_SECRET"
    account_no: "YOUR_KIS_REAL_ACCOUNT_NO"
    product_code: "01"  # Usually 01 for stock accounts
    base_url: "https://openapi.koreainvestment.com:9443"
  
  virtual_account:
    app_key: "YOUR_KIS_VIRTUAL_APP_KEY"
    app_secret: "YOUR_KIS_VIRTUAL_APP_SECRET"
    account_no: "YOUR_KIS_VIRTUAL_ACCOUNT_NO"
    product_code: "01"
    base_url: "https://openapivts.koreainvestment.com:29443"

# Alpha Vantage API
alpha_vantage:
  api_key: "YOUR_ALPHA_VANTAGE_API_KEY"
  tier: "free"  # free, basic, intermediate, premium
  base_url: "https://www.alphavantage.co/query"

# Yahoo Finance (no API key required)
yahoo_finance:
  enabled: true
  
# LS Securities API (if using)
ls_securities:
  real_account:
    app_key: "YOUR_LS_REAL_APP_KEY"
    app_secret: "YOUR_LS_REAL_APP_SECRET"
    account_no: "YOUR_LS_REAL_ACCOUNT_NO"
    base_url: "https://openapi.ls-sec.co.kr:9443"
  
  virtual_account:
    app_key: "YOUR_LS_VIRTUAL_APP_KEY"
    app_secret: "YOUR_LS_VIRTUAL_APP_SECRET"
    account_no: "YOUR_LS_VIRTUAL_ACCOUNT_NO"
    base_url: "https://openapivts.ls-sec.co.kr:29443"

# Telegram Bot (for notifications)
telegram:
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_ids:
    - "YOUR_TELEGRAM_CHAT_ID"
  
# Webhook Configuration
webhooks:
  server:
    host: "0.0.0.0"
    port: 5000
  
  endpoints:
    trading_signals:
      webhook_id: "trading_signals_v1"
      secret: "YOUR_WEBHOOK_SECRET_FOR_TRADING_SIGNALS"
    
    notifications:
      webhook_id: "notifications_v1"
      secret: "YOUR_WEBHOOK_SECRET_FOR_NOTIFICATIONS"
    
    market_data:
      webhook_id: "market_data_v1"
      secret: "YOUR_WEBHOOK_SECRET_FOR_MARKET_DATA"

# Rate Limiting Configuration
rate_limits:
  alpha_vantage:
    requests_per_minute: 5
    requests_per_day: 500
  
  kis_api:
    requests_per_second: 20
    requests_per_minute: 200
    requests_per_day: 10000
  
  yahoo_finance:
    requests_per_second: 2
    requests_per_minute: 60
    requests_per_hour: 1000
  
  telegram:
    messages_per_second: 30
    messages_per_minute: 20

# Health Check Configuration
health_monitoring:
  enabled: true
  check_interval: 60  # seconds
  alert_thresholds:
    warning_error_rate: 20  # percent
    critical_error_rate: 50  # percent
  
  endpoints:
    alpha_vantage:
      url: "https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=AAPL&apikey=demo"
      timeout: 30
    
    kis_api:
      # Custom health check function will be used
      timeout: 30
    
    yahoo_finance:
      # Custom health check function will be used
      timeout: 30