# API Credentials Configuration Template
# 계좌 정보와 API 키 정보 정의
# 작성일: 2025-09-15
# 관리: Helper Agent 독점 관리

version: "1.0"
last_updated: "2025-09-15"

# 브로커 API 설정
brokers:
  kis:
    real_account:
      app_key: "YOUR_REAL_APP_KEY_HERE"
      app_secret: "YOUR_REAL_APP_SECRET_HERE"
      account_number: "YOUR_REAL_ACCOUNT_NUMBER"
      base_url: "https://openapi.koreainvestment.com:9443"

    virtual_account:
      app_key: "YOUR_VIRTUAL_APP_KEY_HERE"
      app_secret: "YOUR_VIRTUAL_APP_SECRET_HERE"
      account_number: "YOUR_VIRTUAL_ACCOUNT_NUMBER"
      base_url: "https://openapivts.koreainvestment.com:29443"

# 외부 데이터 API
external_apis:
  alpha_vantage:
    api_key: "YOUR_ALPHA_VANTAGE_API_KEY_HERE"

  yahoo_finance:
    enabled: true

# 알림 서비스
notification_services:
  telegram:
    bot_token: "YOUR_TELEGRAM_BOT_TOKEN_HERE"
    default_chat_id: "YOUR_TELEGRAM_CHAT_ID_HERE"

# 데이터베이스
databases:
  mongodb:
    connection_string: "mongodb://localhost:27017"
    username: "YOUR_MONGODB_USERNAME"
    password: "YOUR_MONGODB_PASSWORD"