# Trade Agent Configuration
agent:
  name: "Trade Agent"
  version: "1.0.0"
  model: "Claude-3.5-Flash"
  layer: "Service Layer / User Interface Layer"
  
# Core Settings
core:
  max_concurrent_orders: 20
  order_timeout: 30  # seconds
  retry_attempts: 3
  log_level: "INFO"
  
# Trading Parameters
trading:
  order_types:
    - "MARKET"
    - "LIMIT" 
    - "STOP"
    - "STOP_LIMIT"
  execution_mode: "LIVE"  # LIVE, PAPER, SIMULATION
  slippage_tolerance: 0.001  # 0.1%
  partial_fill_handling: true
  
# Risk Management
risk:
  max_position_size: 10000    # USD
  max_daily_loss: 5000        # USD
  max_portfolio_exposure: 0.8  # 80%
  emergency_stop_loss: 0.05   # 5%
  
# Broker Configuration
brokers:
  primary: "interactive_brokers"
  backup: "alpaca"
  connection_timeout: 10  # seconds
  heartbeat_interval: 5   # seconds
  
# Order Management
orders:
  queue_size: 1000
  priority_levels: 3
  batch_execution: false
  order_validation: true
  
# Performance Settings
performance:
  latency_target: 50      # milliseconds
  throughput_target: 100  # orders per minute
  cache_enabled: true
  parallel_execution: true
  
# Monitoring
monitoring:
  fill_rate_tracking: true
  slippage_monitoring: true
  latency_monitoring: true
  pnl_tracking: true
  position_monitoring: true